version: '3.8'

services:
  mongodb:
    image: mongo:5
    container_name: mongodb
    ports:
      - "27017:27017" 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: some-rabbit
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"   
      - "15672:15672"
    hostname: my-rabbit

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_app
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongodb:27017
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672
      RABBITMQ_QUEUE: default_queue
    depends_on:
      - mongodb
      - rabbitmq

volumes:
  mongo_data:
